name: generic-sync

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      # Checks-out repository
      - name: checkout branch
        uses: actions/checkout@v3

      # login docker
      - name: login to dockerhub
        uses: docker/login-action@v2.0.0
        with:
          username: ${{ secrets.DOCKER_UNAME }}
          password: ${{ secrets.DOCKER_PASSWD }}
          
      - name: pull、tag、push
        shell: bash
        run: |
          image="registry.k8s.io/ingress-nginx/controller:v1.3.0"
          docker pull $image
          myTag=${{ secrets.DOCKER_UNAME }}/ingress-nginx-controller:v1.3.0
          docker tag $image $myTag
          docker push $myTag
        
          image="registry.k8s.io/ingress-nginx/kube-webhook-certgen:v1.1.1"
          docker pull $image
          myTag=${{ secrets.DOCKER_UNAME }}/ingress-nginx-webhook-certgen:v1.1.1
          docker tag $image $myTag
          docker push $myTag
          
          image="quay.io/metallb/controller:v0.13.4"
          docker pull $image
          myTag=${{ secrets.DOCKER_UNAME }}/metallb-controller:v0.13.4
          docker tag $image $myTag
          docker push $myTag
          
          image="quay.io/metallb/speaker:v0.13.4"
          docker pull $image
          myTag=${{ secrets.DOCKER_UNAME }}/metallb-speaker:v0.13.4
          docker tag $image $myTag
          docker push $myTag

          image="k8s.gcr.io/defaultbackend-amd64:1.5"
          docker pull $image
          myTag=${{ secrets.DOCKER_UNAME }}/defaultbackend-amd64:1.5
          docker tag $image $myTag
          docker push $myTag
